apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-probe
  labels:
    app: readiness-probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readiness-probe
  template:
    metadata:
      labels:
        app: readiness-probe
    spec:
      containers:
        - name: readiness-probe
          image: us-central1-docker.pkg.dev/$GCP_PROJECT/tmp/k8s-probes:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000