apiVersion: apps/v1
kind: Deployment
metadata:
  name: startup-probe
  labels:
    app: startup-probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: startup-probe
  template:
    metadata:
      labels:
        app: startup-probe
    spec:
      containers:
        - name: startup-probe
          startupProbe:
            httpGet:
              path: /startup
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /liveness
              port: 3000
            initialDelaySeconds: 15
          image: us-central1-docker.pkg.dev/$GCP_PROJECT/tmp/k8s-probes:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000